{
  "comments": [
    {
      "key": {
        "uuid": "fabf19d9_5d866fba",
        "filename": "share/templates/helpers/pref_table.tt",
        "patchSetId": 2
      },
      "lineNbr": 173,
      "author": {
        "id": 1000009
      },
      "writtenOn": "2018-05-15T14:11:04Z",
      "side": 1,
      "message": "Just wonder - do you know the reason of this exceptions? I don\u0027t...",
      "range": {
        "startLine": 171,
        "startChar": 0,
        "endLine": 173,
        "endChar": 9
      },
      "revId": "c7285bd60937219bc3bc1b7ab29b1ed7bc58c08b",
      "serverId": "85315e57-5f03-49c3-83f8-201ae2313a75",
      "unresolved": false
    }
  ]
}